### ISSUE TITLE
Multiples

### ISSUE THREAD

**Issue by joeblew99** [SaturnsVoid/SimpleLicensing#2]
When a license file is stolen you end up with the proper buyer and the stolen one having the same key dates file.

So you need to detect it. Are there more than 2 Mac addresses ?
See the history so you can see the proper buyer.
Upgrade the proper buyer to a new license, and revoke the old one.

**Comment by SaturnsVoid** [comment]
This is an issue with this style of doing it, Though the issue is taken care of by using a HWID (Hardware ID) like in my example here; https://github.com/SaturnsVoid/HWID-Based-License-System

**Comment by joeblew99** [comment]
true. i see your point.
I will try it out...
